version: '3'
services:
  server1:
    build:
      context: .
      dockerfile: Dockerfile.server1
    ports:
      - "8080:80"
    networks:
      default:
        aliases:
          - server1.example.com

  server2:
    build:
      context: .
      dockerfile: Dockerfile.server2
    ports:
      - "8081:80"
    networks:
      default:
        aliases:
          - server2.example.com
